services:
  - type: web
    name: newrelic-query-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: NRAK-75C6I503C080UJ60CA73CH1XBTT
        sync: false
      - key: 1896682
        sync: false