services:
  - type: web
    name: newrelic-query-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: NEW_RELIC_API_KEY
        sync: false
      - key: NEW_RELIC_ACCOUNT_ID
        sync: false